language: ruby
cache: bundler
addons:
  postgresql: "12"
apt:
  packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - PGUSER=travis
before_install:
  - nvm install --lts
  - npm install yarn
services:
  - postgresql
before_script:
  - psql -c 'create database plow_report_test;' -U postgres
  - yarn install