language: ruby
cache: bundler
addons:
  postgresql: "13"
before_install:
  - nvm install --lts
  - npm install yarn
services:
  - postgresql
before_script:
  - psql -c 'create database plow_report_test;' -U postgres
  - yarn install