dist: focal
language: ruby
cache: bundler
services:
  - postgresql
before_install:
  - nvm install --lts
  - npm install yarn
before_script:
  - psql -c 'create database plow_report_test;'
  - yarn install