language: ruby
cache: bundler
addons:
  postgresql: '12'
apt:
  packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
    - PGVER=12
    - PGPORT=5433
before_install:
  - nvm install --lts
  - npm install yarn
before_script:
  - psql -c 'create database plow_report_test;'
  - yarn install