dist: focal
language: ruby
cache: bundler
addons:
  postgresql: '13'
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
env:
  global:
    - PGVER=13
    - PGPORT=5433
before_install:
  - nvm install --lts
  - npm install yarn
before_script:
  - psql -c 'create database plow_report_test;'
  - yarn install